voices = {
    "Clara": {
        "gender": "Female",
        "languageCode": "en-US",
        "languageName": "English",
        "provider": "Naver",
        "limit": 500,
        "quality": "High",
        "translates": False,
        "url": "https://dict.naver.com/api/nvoice?service=dictionary&speech_fmt=mp3&speaker=clara&text={text}",
    },
    "Matt": {
        "gender": "Male",
        "languageCode": "en-US",
        "languageName": "English",
        "provider": "Naver",
        "limit": 500,
        "quality": "High",
        "translates": False,
        "url": "https://dict.naver.com/api/nvoice?service=dictionary&speech_fmt=mp3&speaker=matt&text={text}",
    },
    "Carmen": {
        "gender": "Female",
        "languageCode": "es-MX",
        "languageName": "Spanish",
        "provider": "Naver",
        "limit": 500,
        "quality": "High",
        "translates": False,
        "url": "https://dict.naver.com/api/nvoice?service=dictionary&speech_fmt=mp3&speaker=carmen&text={text}",
    },
    "Jose": {
        "gender": "Male",
        "languageCode": "es-MX",
        "languageName": "Spanish",
        "provider": "Naver",
        "limit": 500,
        "quality": "High",
        "translates": False,
        "url": "https://dict.naver.com/api/nvoice?service=dictionary&speech_fmt=mp3&speaker=jose&text={text}",
    },
    "Shinji": {
        "gender": "Male",
        "languageCode": "ja-JP",
        "languageName": "Japanese",
        "provider": "Naver",
        "limit": 200,
        "quality": "High",
        "translates": False,
        "url": "https://dict.naver.com/api/nvoice?service=dictionary&speech_fmt=mp3&speaker=shinji&text={text}",
    },
    "Kyuri": {
        "gender": "Female",
        "languageCode": "ko-KR",
        "languageName": "Korean",
        "provider": "Naver",
        "limit": 250,
        "quality": "High",
        "translates": False,
        "url": "https://dict.naver.com/api/nvoice?service=dictionary&speech_fmt=mp3&speaker=kyuri&text={text}",
    },
    "Jinho": {
        "gender": "Male",
        "languageCode": "ko-KR",
        "languageName": "Korean",
        "provider": "Naver",
        "limit": 250,
        "quality": "High",
        "translates": False,
        "url": "https://dict.naver.com/api/nvoice?service=dictionary&speech_fmt=mp3&speaker=jinho&text={text}",
    },
    "Meimei": {
        "gender": "Female",
        "languageCode": "zh-CN",
        "languageName": "Chinese (simplified characters)",
        "provider": "Naver",
        "limit": 200,
        "quality": "High",
        "translates": False,
        "url": "https://dict.naver.com/api/nvoice?service=dictionary&speech_fmt=mp3&speaker=meimei&text={text}",
    },
    "Liangliang": {
        "gender": "Male",
        "languageCode": "zh-CN",
        "languageName": "Chinese (simplified characters)",
        "provider": "Naver",
        "limit": 150,
        "quality": "High",
        "translates": False,
        "url": "https://dict.naver.com/api/nvoice?service=dictionary&speech_fmt=mp3&speaker=liangliang&text={text}",
    },
    "Chiahua": {
        "gender": "Female",
        "languageCode": "zh-CN",
        "languageName": "Chinese (traditional characters)",
        "provider": "Naver",
        "limit": 150,
        "quality": "High",
        "translates": False,
        "url": "https://dict.naver.com/api/nvoice?service=dictionary&speech_fmt=mp3&speaker=chiahua&text={text}",
    },
    "Filiz": {
        "gender": "Female",
        "languageCode": "tr-TR",
        "languageName": "Turkish",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Filiz&text={text}",
    },
    "Astrid": {
        "gender": "Female",
        "languageCode": "sv-SE",
        "languageName": "Swedish",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Astrid&text={text}",
    },
    "Tatyana": {
        "gender": "Female",
        "languageCode": "ru-RU",
        "languageName": "Russian",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Tatyana&text={text}",
    },
    "Maxim": {
        "gender": "Male",
        "languageCode": "ru-RU",
        "languageName": "Russian",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Maxim&text={text}",
    },
    "Ines": {
        "gender": "Female",
        "languageCode": "pt-PT",
        "languageName": "Portuguese",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Ines&text={text}",
    },
    "Cristiano": {
        "gender": "Male",
        "languageCode": "pt-PT",
        "languageName": "Portuguese",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Cristiano&text={text}",
    },
    "Vitoria": {
        "gender": "Female",
        "languageCode": "pt-BR",
        "languageName": "Brazilian Portuguese",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Vitoria&text={text}",
    },
    "Ricardo": {
        "gender": "Male",
        "languageCode": "pt-BR",
        "languageName": "Brazilian Portuguese",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Ricardo&text={text}",
    },
    "Maja": {
        "gender": "Female",
        "languageCode": "pl-PL",
        "languageName": "Polish",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Maja&text={text}",
    },
    "Jan": {
        "gender": "Male",
        "languageCode": "pl-PL",
        "languageName": "Polish",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Jan&text={text}",
    },
    "Jacek": {
        "gender": "Male",
        "languageCode": "pl-PL",
        "languageName": "Polish",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Jacek&text={text}",
    },
    "Ewa": {
        "gender": "Female",
        "languageCode": "pl-PL",
        "languageName": "Polish",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Ewa&text={text}",
    },
    "Ruben": {
        "gender": "Male",
        "languageCode": "nl-NL",
        "languageName": "Dutch",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Ruben&text={text}",
    },
    "Lotte": {
        "gender": "Female",
        "languageCode": "nl-NL",
        "languageName": "Dutch",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Lotte&text={text}",
    },
    "Liv": {
        "gender": "Female",
        "languageCode": "nb-NO",
        "languageName": "Norwegian",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Liv&text={text}",
    },
    "Seoyeon": {
        "gender": "Female",
        "languageCode": "ko-KR",
        "languageName": "Korean",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Seoyeon&text={text}",
    },
    "Takumi": {
        "gender": "Male",
        "languageCode": "ja-JP",
        "languageName": "Japanese",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Takumi&text={text}",
    },
    "Mizuki": {
        "gender": "Female",
        "languageCode": "ja-JP",
        "languageName": "Japanese",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Mizuki&text={text}",
    },
    "Giorgio": {
        "gender": "Male",
        "languageCode": "it-IT",
        "languageName": "Italian",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Giorgio&text={text}",
    },
    "Carla": {
        "gender": "Female",
        "languageCode": "it-IT",
        "languageName": "Italian",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Carla&text={text}",
    },
    "Bianca": {
        "gender": "Female",
        "languageCode": "it-IT",
        "languageName": "Italian",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Bianca&text={text}",
    },
    "Karl": {
        "gender": "Male",
        "languageCode": "is-IS",
        "languageName": "Icelandic",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Karl&text={text}",
    },
    "Dora": {
        "gender": "Female",
        "languageCode": "is-IS",
        "languageName": "Icelandic",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Dora&text={text}",
    },
    "Mathieu": {
        "gender": "Male",
        "languageCode": "fr-FR",
        "languageName": "French",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Mathieu&text={text}",
    },
    "Celine": {
        "gender": "Female",
        "languageCode": "fr-FR",
        "languageName": "French",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Celine&text={text}",
    },
    "Chantal": {
        "gender": "Female",
        "languageCode": "fr-CA",
        "languageName": "Canadian French",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Chantal&text={text}",
    },
    "Penelope": {
        "gender": "Female",
        "languageCode": "es-US",
        "languageName": "US Spanish",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Penelope&text={text}",
    },
    "Miguel": {
        "gender": "Male",
        "languageCode": "es-US",
        "languageName": "US Spanish",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Miguel&text={text}",
    },
    "Mia": {
        "gender": "Female",
        "languageCode": "es-MX",
        "languageName": "Mexican, Spanish",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Mia&text={text}",
    },
    "Enrique": {
        "gender": "Male",
        "languageCode": "es-ES",
        "languageName": "Castilian Spanish",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Enrique&text={text}",
    },
    "Conchita": {
        "gender": "Female",
        "languageCode": "es-ES",
        "languageName": "Castilian Spanish",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Conchita&text={text}",
    },
    "Geraint": {
        "gender": "Male",
        "languageCode": "en-GB-WLS",
        "languageName": "Welsh English",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Geraint&text={text}",
    },
    "Salli": {
        "gender": "Female",
        "languageCode": "en-US",
        "languageName": "US English",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Salli&text={text}",
    },
    "Matthew": {
        "gender": "Male",
        "languageCode": "en-US",
        "languageName": "US English",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Matthew&text={text}",
    },
    "Kimberly": {
        "gender": "Female",
        "languageCode": "en-US",
        "languageName": "US English",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Kimberly&text={text}",
    },
    "Kendra": {
        "gender": "Female",
        "languageCode": "en-US",
        "languageName": "US English",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Kendra&text={text}",
    },
    "Justin": {
        "gender": "Male",
        "languageCode": "en-US",
        "languageName": "US English",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Justin&text={text}",
    },
    "Joey": {
        "gender": "Male",
        "languageCode": "en-US",
        "languageName": "US English",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Joey&text={text}",
    },
    "Joanna": {
        "gender": "Female",
        "languageCode": "en-US",
        "languageName": "US English",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Joanna&text={text}",
    },
    "Ivy": {
        "gender": "Female",
        "languageCode": "en-US",
        "languageName": "US English",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Ivy&text={text}",
    },
    "Raveena": {
        "gender": "Female",
        "languageCode": "en-IN",
        "languageName": "Indian English",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Raveena&text={text}",
    },
    "Aditi": {
        "gender": "Female",
        "languageCode": "en-IN",
        "languageName": "Indian English",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Aditi&text={text}",
    },
    "Emma": {
        "gender": "Female",
        "languageCode": "en-GB",
        "languageName": "British English",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Emma&text={text}",
    },
    "Brian": {
        "gender": "Male",
        "languageCode": "en-GB",
        "languageName": "British English",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Brian&text={text}",
    },
    "Amy": {
        "gender": "Female",
        "languageCode": "en-GB",
        "languageName": "British English",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Amy&text={text}",
    },
    "Russell": {
        "gender": "Male",
        "languageCode": "en-AU",
        "languageName": "Australian English",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Russell&text={text}",
    },
    "Nicole": {
        "gender": "Female",
        "languageCode": "en-AU",
        "languageName": "Australian English",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Nicole&text={text}",
    },
    "Vicki": {
        "gender": "Female",
        "languageCode": "de-DE",
        "languageName": "German",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Vicki&text={text}",
    },
    "Marlene": {
        "gender": "Female",
        "languageCode": "de-DE",
        "languageName": "German",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Marlene&text={text}",
    },
    "Hans": {
        "gender": "Male",
        "languageCode": "de-DE",
        "languageName": "German",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Hans&text={text}",
    },
    "Naja": {
        "gender": "Female",
        "languageCode": "da-DK",
        "languageName": "Danish",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Naja&text={text}",
    },
    "Mads": {
        "gender": "Male",
        "languageCode": "da-DK",
        "languageName": "Danish",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Mads&text={text}",
    },
    "Gwyneth": {
        "gender": "Female",
        "languageCode": "cy-GB",
        "languageName": "Welsh",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Gwyneth&text={text}",
    },
    "Zhiyu": {
        "gender": "Female",
        "languageCode": "cmn-CN",
        "languageName": "Chinese, Mandarin",
        "provider": "Polly",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Zhiyu&text={text}",
    },
    "Sofia": {
        "gender": "Female",
        "languageCode": "es-LA",
        "languageName": "Spanish",
        "provider": "Watson",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=es-LA_SofiaVoice&text={text}",
    },
    "Isabela": {
        "gender": "Female",
        "languageCode": "pt-BR",
        "languageName": "Brazilian Portuguese",
        "provider": "Watson",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=pt-BR_IsabelaVoice&text={text}",
    },
    "Kyrie": {
        "gender": "Male",
        "languageCode": "en-US",
        "languageName": "US English",
        "provider": "Watson",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-US_MichaelVoice&text={text}",
    },
    "Emi": {
        "gender": "Female",
        "languageCode": "ja-JP",
        "languageName": "Japanese (日本語)",
        "provider": "Watson",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=ja-JP_EmiVoice&text={text}",
    },
    "Allison": {
        "gender": "Female",
        "languageCode": "en-US",
        "languageName": "US English",
        "provider": "Watson",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-US_AllisonVoice&text={text}",
    },
    "Renee": {
        "gender": "Female",
        "languageCode": "fr-FR",
        "languageName": "French (français)",
        "provider": "Watson",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=fr-FR_ReneeVoice&text={text}",
    },
    "Francesca": {
        "gender": "Female",
        "languageCode": "it-IT",
        "languageName": "Italian (italiano)",
        "provider": "Watson",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=it-IT_FrancescaVoice&text={text}",
    },
    "Laura": {
        "gender": "Female",
        "languageCode": "es-ES",
        "languageName": "Castilian Spanish (español castellano)",
        "provider": "Watson",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=es-ES_LauraVoice&text={text}",
    },
    "Birgit": {
        "gender": "Female",
        "languageCode": "de-DE",
        "languageName": "German",
        "provider": "Watson",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=de-DE_BirgitVoice&text={text}",
    },
    "Alejandro": {
        "gender": "Male",
        "languageCode": "es-ES",
        "languageName": "Spanish",
        "provider": "Watson",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=es-ES_EnriqueVoice&text={text}",
    },
    "Dieter": {
        "gender": "Male",
        "languageCode": "de-DE",
        "languageName": "German",
        "provider": "Watson",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=de-DE_DieterVoice&text={text}",
    },
    "Lisa": {
        "gender": "Female",
        "languageCode": "en-US",
        "languageName": "US English",
        "provider": "Watson",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-US_LisaVoice&text={text}",
    },
    "Kate": {
        "gender": "Female",
        "languageCode": "en-GB",
        "languageName": "British English",
        "provider": "Watson",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-GB_KateVoice&text={text}",
    },
    "Luciana": {
        "gender": "Female",
        "languageCode": "es-US",
        "languageName": "American Spanish",
        "provider": "Watson",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=es-US_SofiaVoice&text={text}",
    },
    "Rosalinda": {
        "languageCode": "es-ES",
        "languageName": "Castilian Spanish",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=es-ES-Standard-A&text={text}",
    },
    "Gianna": {
        "languageCode": "it-IT",
        "languageName": "Italian (italiano)",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=it-IT-Standard-A&text={text}",
    },
    "Valentina": {
        "gender": "Female",
        "languageCode": "it-IT",
        "languageName": "Italian",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=it-IT-Wavenet-A&text={text}",
    },
    "Koharu": {
        "languageCode": "ja-JP",
        "languageName": "Japanese",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=ja-JP-Standard-A&text={text}",
    },
    "Miho": {
        "gender": "Female",
        "languageCode": "ja-JP",
        "languageName": "Japanese",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=ja-JP-Wavenet-A&text={text}",
    },
    "Heosu": {
        "languageCode": "ko-KR",
        "languageName": "Korean",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=ko-KR-Standard-A&text={text}",
    },
    "Grace": {
        "languageCode": "ko-KR",
        "languageName": "Korean",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=ko-KR-Wavenet-A&text={text}",
    },
    "Alice": {
        "languageCode": "pt-BR",
        "languageName": "Brazilian Portuguese",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=pt-BR-Standard-A&text={text}",
    },
    "Zehra": {
        "languageCode": "tr-TR",
        "languageName": "Turkish",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=tr-TR-Standard-A&text={text}",
    },
    "Elsa": {
        "languageCode": "sv-SE",
        "languageName": "Swedish",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=sv-SE-Standard-A&text={text}",
    },
    "Annemieke": {
        "languageCode": "nl-NL",
        "languageName": "Dutch",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=nl-NL-Standard-A&text={text}",
    },
    "Eva": {
        "gender": "Female",
        "languageCode": "nl-NL",
        "languageName": "Dutch",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=nl-NL-Wavenet-A&text={text}",
    },
    "Carter": {
        "languageCode": "en-US",
        "languageName": "US English",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-US-Wavenet-A&text={text}",
    },
    "Paul": {
        "languageCode": "en-US",
        "languageName": "US English",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-US-Wavenet-B&text={text}",
    },
    "Evelyn": {
        "languageCode": "en-US",
        "languageName": "US English",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-US-Wavenet-C&text={text}",
    },
    "Liam": {
        "languageCode": "en-US",
        "languageName": "US English",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-US-Wavenet-D&text={text}",
    },
    "Jasmine": {
        "languageCode": "en-US",
        "languageName": "US English",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-US-Wavenet-E&text={text}",
    },
    "Madison": {
        "languageCode": "en-US",
        "languageName": "US English",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-US-Wavenet-F&text={text}",
    },
    "Layla": {
        "languageCode": "en-GB",
        "languageName": "British English",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-GB-Standard-A&text={text}",
    },
    "Ali": {
        "languageCode": "en-GB",
        "languageName": "British English",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-GB-Standard-B&text={text}",
    },
    "Scarlett": {
        "languageCode": "en-GB",
        "languageName": "British English",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-GB-Standard-C&text={text}",
    },
    "Oliver": {
        "languageCode": "en-GB",
        "languageName": "British English",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-GB-Standard-D&text={text}",
    },
    "Bella": {
        "languageCode": "en-GB",
        "languageName": "British English",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-GB-Wavenet-A&text={text}",
    },
    "John": {
        "languageCode": "en-GB",
        "languageName": "British English",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-GB-Wavenet-B&text={text}",
    },
    "Victoria": {
        "languageCode": "en-GB",
        "languageName": "British English",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-GB-Wavenet-C&text={text}",
    },
    "Ron": {
        "languageCode": "en-GB",
        "languageName": "British English",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-GB-Wavenet-D&text={text}",
    },
    "Mark": {
        "languageCode": "en-US",
        "languageName": "US English",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-US-Standard-B&text={text}",
    },
    "Vanessa": {
        "languageCode": "en-US",
        "languageName": "US English",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-US-Standard-C&text={text}",
    },
    "Zachary": {
        "languageCode": "en-US",
        "languageName": "US English",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-US-Standard-D&text={text}",
    },
    "Audrey": {
        "languageCode": "en-US",
        "languageName": "US English",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-US-Standard-E&text={text}",
    },
    "Karolina": {
        "languageCode": "de-DE",
        "languageName": "German",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=de-DE-Standard-A&text={text}",
    },
    "Albert": {
        "languageCode": "de-DE",
        "languageName": "German",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=de-DE-Standard-B&text={text}",
    },
    "Angelika": {
        "languageCode": "de-DE",
        "languageName": "German",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=de-DE-Wavenet-A&text={text}",
    },
    "Oskar": {
        "languageCode": "de-DE",
        "languageName": "German",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=de-DE-Wavenet-B&text={text}",
    },
    "Nina": {
        "languageCode": "de-DE",
        "languageName": "German",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=de-DE-Wavenet-C&text={text}",
    },
    "Sebastian": {
        "languageCode": "de-DE",
        "languageName": "German",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=de-DE-Wavenet-D&text={text}",
    },
    "Zoe": {
        "languageCode": "en-AU",
        "languageName": "Australian English",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-AU-Standard-A&text={text}",
    },
    "Luke": {
        "languageCode": "en-AU",
        "languageName": "Australian English",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-AU-Standard-B&text={text}",
    },
    "Samantha": {
        "languageCode": "en-AU",
        "languageName": "Australian English",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-AU-Wavenet-A&text={text}",
    },
    "Steve": {
        "languageCode": "en-AU",
        "languageName": "Australian English",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-AU-Wavenet-B&text={text}",
    },
    "Courtney": {
        "languageCode": "en-AU",
        "languageName": "Australian English",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-AU-Wavenet-C&text={text}",
    },
    "Jayden": {
        "languageCode": "en-AU",
        "languageName": "Australian English",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-AU-Wavenet-D&text={text}",
    },
    "Ashleigh": {
        "languageCode": "en-AU",
        "languageName": "Australian English",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-AU-Standard-C&text={text}",
    },
    "Daniel": {
        "languageCode": "en-AU",
        "languageName": "Australian English",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-AU-Standard-D&text={text}",
    },
    "Juliette": {
        "languageCode": "fr-CA",
        "languageName": "Canadian French",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=fr-CA-Standard-A&text={text}",
    },
    "Felix": {
        "languageCode": "fr-CA",
        "languageName": "Canadian French",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=fr-CA-Standard-B&text={text}",
    },
    "Camille": {
        "languageCode": "fr-CA",
        "languageName": "Canadian French",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=fr-CA-Standard-C&text={text}",
    },
    "Jacques": {
        "languageCode": "fr-CA",
        "languageName": "Canadian French",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=fr-CA-Standard-D&text={text}",
    },
    "Yvonne": {
        "languageCode": "fr-FR",
        "languageName": "French (français)",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=fr-FR-Standard-C&text={text}",
    },
    "Gaspard": {
        "languageCode": "fr-FR",
        "languageName": "French (français)",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "Low",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=fr-FR-Standard-D&text={text}",
    },
    "Emilie": {
        "languageCode": "fr-FR",
        "languageName": "French (français)",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=fr-FR-Wavenet-A&text={text}",
    },
    "Marcel": {
        "languageCode": "fr-FR",
        "languageName": "French (français)",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=fr-FR-Wavenet-B&text={text}",
    },
    "Brigitte": {
        "languageCode": "fr-FR",
        "languageName": "French (français)",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=fr-FR-Wavenet-C&text={text}",
    },
    "Simon": {
        "languageCode": "fr-FR",
        "languageName": "French (français)",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=fr-FR-Wavenet-D&text={text}",
    },
    "Marie": {
        "gender": "Female",
        "languageCode": "da-DK",
        "languageName": "Danish",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=da-DK-Wavenet-A&text={text}",
    },
    "Amelia": {
        "gender": "Female",
        "languageCode": "pl-PL",
        "languageName": "Polish (Poland)",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=pl-PL-Wavenet-A&text={text}",
    },
    "Stanislaw": {
        "gender": "Male",
        "languageCode": "pl-PL",
        "languageName": "Polish (Poland)",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=pl-PL-Wavenet-B&text={text}",
    },
    "Tomasz": {
        "gender": "Male",
        "languageCode": "pl-PL",
        "languageName": "Polish (Poland)",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=pl-PL-Wavenet-C&text={text}",
    },
    "Klaudia": {
        "gender": "Female",
        "languageCode": "pl-PL",
        "languageName": "Polish (Poland)",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=pl-PL-Wavenet-D&text={text}",
    },
    "Beatriz": {
        "languageName": "Portuguese (Portugal)",
        "languageCode": "pt-PT",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=pt-PT-Wavenet-A&text={text}",
    },
    "Francisco": {
        "languageName": "Portuguese (Portugal)",
        "languageCode": "pt-PT",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=pt-PT-Wavenet-B&text={text}",
    },
    "Lucas": {
        "languageName": "Portuguese (Portugal)",
        "languageCode": "pt-PT",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=pt-PT-Wavenet-C&text={text}",
    },
    "Carolina": {
        "languageName": "Portuguese (Portugal)",
        "languageCode": "pt-PT",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=pt-PT-Wavenet-D&text={text}",
    },
    "Masha": {
        "languageName": "Russian (Russia)",
        "languageCode": "ru-RU",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=ru-RU-Wavenet-A&text={text}",
    },
    "Ilya": {
        "languageName": "Russian (Russia)",
        "languageCode": "ru-RU",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=ru-RU-Wavenet-B&text={text}",
    },
    "Alena": {
        "languageName": "Russian (Russia)",
        "languageCode": "ru-RU",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=ru-RU-Wavenet-C&text={text}",
    },
    "Petr": {
        "languageName": "Russian (Russia)",
        "languageCode": "ru-RU",
        "gender": "Male",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=ru-RU-Wavenet-D&text={text}",
    },
    "Eliska": {
        "languageName": "Slovak (Slovakia)",
        "languageCode": "sk-SK",
        "gender": "Female",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=sk-SK-Wavenet-A&text={text}",
    },
    "Yagmur": {
        "gender": "Female",
        "languageCode": "tr-TR",
        "languageName": "Turkish (Turkey)",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=tr-TR-Wavenet-A&text={text}",
    },
    "Mehmet": {
        "gender": "Male",
        "languageCode": "tr-TR",
        "languageName": "Turkish (Turkey)",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=tr-TR-Wavenet-B&text={text}",
    },
    "Miray": {
        "gender": "Female",
        "languageCode": "tr-TR",
        "languageName": "Turkish (Turkey)",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=tr-TR-Wavenet-C&text={text}",
    },
    "Elif": {
        "gender": "Female",
        "languageCode": "tr-TR",
        "languageName": "Turkish (Turkey)",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=tr-TR-Wavenet-D&text={text}",
    },
    "Enes": {
        "gender": "Male",
        "languageCode": "tr-TR",
        "languageName": "Turkish (Turkey)",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=tr-TR-Wavenet-E&text={text}",
    },
    "Vladislav": {
        "gender": "Male",
        "languageCode": "uk-UA",
        "languageName": "Ukrainian (Ukraine)",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=uk-UA-Wavenet-A&text={text}",
    },
    "Aisha": {
        "gender": "Female",
        "languageCode": "ar-XA",
        "languageName": "Arabic",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=ar-XA-Wavenet-A&text={text}",
    },
    "Ahmad": {
        "gender": "Male",
        "languageCode": "ar-XA",
        "languageName": "Arabic",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=ar-XA-Wavenet-B&text={text}",
    },
    "Hazim": {
        "gender": "Male",
        "languageCode": "ar-XA",
        "languageName": "Arabic",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=ar-XA-Wavenet-C&text={text}",
    },
    "Silvia": {
        "gender": "Female",
        "languageCode": "cs-CZ",
        "languageName": "Czech",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=cs-CZ-Wavenet-A&text={text}",
    },
    "Lars": {
        "gender": "Male",
        "languageCode": "nl-NL",
        "languageName": "Dutch",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=nl-NL-Wavenet-B&text={text}",
    },
    "Marc": {
        "gender": "Male",
        "languageCode": "nl-NL",
        "languageName": "Dutch",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=nl-NL-Wavenet-C&text={text}",
    },
    "Verona": {
        "gender": "Female",
        "languageCode": "nl-NL",
        "languageName": "Dutch",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=nl-NL-Wavenet-D&text={text}",
    },
    "Lotte": {
        "gender": "Female",
        "languageCode": "nl-NL",
        "languageName": "Dutch",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=nl-NL-Wavenet-E&text={text}",
    },
    "Anushri": {
        "gender": "Female",
        "languageCode": "en-IN",
        "languageName": "English (India)",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-IN-Wavenet-A&text={text}",
    },
    "Sundar": {
        "gender": "Male",
        "languageCode": "en-IN",
        "languageName": "English (India)",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-IN-Wavenet-B&text={text}",
    },
    "Satya": {
        "gender": "Male",
        "languageCode": "en-IN",
        "languageName": "English (India)",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=en-IN-Wavenet-C&text={text}",
    },
    "Tala": {
        "gender": "Female",
        "languageCode": "fil-PH",
        "languageName": "Filipino",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=fil-PH-Wavenet-A&text={text}",
    },
    "Marianne": {
        "gender": "Female",
        "languageCode": "fi-FI",
        "languageName": "Finnish",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=fi-FI-Wavenet-A&text={text}",
    },
    "Thalia": {
        "gender": "Female",
        "languageCode": "el-GR",
        "languageName": "Greek",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=el-GR-Wavenet-A&text={text}",
    },
    "Sneha": {
        "gender": "Female",
        "languageCode": "hi-IN",
        "languageName": "Hindi",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=hi-IN-Wavenet-A&text={text}",
    },
    "Arnav": {
        "gender": "Male",
        "languageCode": "hi-IN",
        "languageName": "Hindi",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=hi-IN-Wavenet-B&text={text}",
    },
    "Aadhav": {
        "gender": "Male",
        "languageCode": "hi-IN",
        "languageName": "Hindi",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=hi-IN-Wavenet-C&text={text}",
    },
    "Ishtevan": {
        "gender": "Female",
        "languageCode": "hu-HU",
        "languageName": "Hungarian",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=hu-HU-Wavenet-A&text={text}",
    },
    "Anisa": {
        "gender": "Female",
        "languageCode": "id-ID",
        "languageName": "Indonesian",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=id-ID-Wavenet-A&text={text}",
    },
    "Budi": {
        "gender": "Male",
        "languageCode": "id-ID",
        "languageName": "Indonesian",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=id-ID-Wavenet-B&text={text}",
    },
    "Bayu": {
        "gender": "Male",
        "languageCode": "id-ID",
        "languageName": "Indonesian",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=id-ID-Wavenet-C&text={text}",
    },
    "Stella": {
        "gender": "Female",
        "languageCode": "it-IT",
        "languageName": "Italian",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=it-IT-Wavenet-B&text={text}",
    },
    "Alessandro": {
        "gender": "Male",
        "languageCode": "it-IT",
        "languageName": "Italian",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=it-IT-Wavenet-C&text={text}",
    },
    "Luca": {
        "gender": "Male",
        "languageCode": "it-IT",
        "languageName": "Italian",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=it-IT-Wavenet-D&text={text}",
    },
    "Eiko": {
        "gender": "Female",
        "languageCode": "ja-JP",
        "languageName": "Japanese",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=ja-JP-Wavenet-B&text={text}",
    },
    "Haruto": {
        "gender": "Male",
        "languageCode": "ja-JP",
        "languageName": "Japanese",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=ja-JP-Wavenet-C&text={text}",
    },
    "Eichi": {
        "gender": "Male",
        "languageCode": "ja-JP",
        "languageName": "Japanese",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=ja-JP-Wavenet-D&text={text}",
    },
    "Meili": {
        "gender": "Female",
        "languageCode": "cmn-CN",
        "languageName": "Mandarin Chinese",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=cmn-CN-Wavenet-A&text={text}",
    },
    "Wang": {
        "gender": "Male",
        "languageCode": "cmn-CN",
        "languageName": "Mandarin Chinese",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=cmn-CN-Wavenet-B&text={text}",
    },
    "Bai": {
        "gender": "Male",
        "languageCode": "cmn-CN",
        "languageName": "Mandarin Chinese",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=cmn-CN-Wavenet-C&text={text}",
    },
    "Mingli": {
        "gender": "Female",
        "languageCode": "cmn-CN",
        "languageName": "Mandarin Chinese",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=cmn-CN-Wavenet-D&text={text}",
    },
    "Nora": {
        "gender": "Female",
        "languageCode": "nb-no",
        "languageName": "Norwegian",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=nb-no-Wavenet-E&text={text}",
    },
    "Malena": {
        "gender": "Female",
        "languageCode": "nb-no",
        "languageName": "Norwegian",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=nb-no-Wavenet-A&text={text}",
    },
    "Jacob": {
        "gender": "Male",
        "languageCode": "nb-no",
        "languageName": "Norwegian",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=nb-no-Wavenet-B&text={text}",
    },
    "Thea": {
        "gender": "Female",
        "languageCode": "nb-no",
        "languageName": "Norwegian",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=nb-no-Wavenet-C&text={text}",
    },
    "Aksel": {
        "gender": "Male",
        "languageCode": "nb-no",
        "languageName": "Norwegian",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=nb-no-Wavenet-D&text={text}",
    },
    "Linh": {
        "gender": "Female",
        "languageCode": "vi-VN",
        "languageName": "Vietnamese",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=vi-VN-Wavenet-A&text={text}",
    },
    "Nguyen": {
        "gender": "Male",
        "languageCode": "vi-VN",
        "languageName": "Vietnamese",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=vi-VN-Wavenet-B&text={text}",
    },
    "Phuong": {
        "gender": "Female",
        "languageCode": "vi-VN",
        "languageName": "Vietnamese",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=vi-VN-Wavenet-C&text={text}",
    },
    "Viet": {
        "gender": "Male",
        "languageCode": "vi-VN",
        "languageName": "Vietnamese",
        "provider": "Google",
        "limit": 1000,
        "quality": "High",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=vi-VN-Wavenet-D&text={text}",
    },
    "Tracy": {
        "languageCode": "zh-HK",
        "languageName": "Hong Kong (traditional characters)",
        "gender": "Female",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Tracy&text={text}",
    },
    "Danny": {
        "languageCode": "zh-HK",
        "languageName": "Hong Kong (traditional characters)",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Danny&text={text}",
    },
    "Huihui": {
        "languageCode": "zh-CN",
        "languageName": "Chinese (simplified characters)",
        "gender": "Female",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Huihui&text={text}",
    },
    "Yaoyao": {
        "languageCode": "zh-CN",
        "languageName": "Chinese (simplified characters)",
        "gender": "Female",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Yaoyao&text={text}",
    },
    "Kangkang": {
        "languageCode": "zh-CN",
        "languageName": "Chinese (simplified characters)",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Kangkang&text={text}",
    },
    "Hanhan": {
        "languageCode": "zh-TW",
        "languageName": "Taiwanese (traditional characters)",
        "gender": "Female",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=HanHan&text={text}",
    },
    "Zhiwei": {
        "languageCode": "zh-TW",
        "languageName": "Taiwanese (traditional characters)",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Zhiwei&text={text}",
    },
    "Doron": {
        "languageCode": "he-IL",
        "languageName": "Hebrew",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Asaf&text={text}",
    },
    "An": {
        "languageCode": "vi-VN",
        "languageName": "Vietnamese",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=An&text={text}",
    },
    "Stefanos": {
        "languageCode": "el-GR",
        "languageName": "Greek",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Stefanos&text={text}",
    },
    "Filip": {
        "languageCode": "sk-SK",
        "languageName": "Slovak",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Filip&text={text}",
    },
    "Ivan": {
        "languageCode": "bg-BG",
        "languageName": "Bulgarian",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Ivan&text={text}",
    },
    "Heidi": {
        "languageCode": "fi-FI",
        "languageName": "Finnish",
        "gender": "Female",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Heidi&text={text}",
    },
    "Herena": {
        "languageCode": "ca-ES",
        "languageName": "Catalan (Spain)",
        "gender": "Female",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Herena&text={text}",
    },
    "Kalpana": {
        "languageCode": "hi-IN",
        "languageName": "Hindi (India)",
        "gender": "Female",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Kalpana&text={text}",
    },
    "Hemant": {
        "languageCode": "hi-IN",
        "languageName": "Hindi (India)",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Hemant&text={text}",
    },
    "Matej": {
        "languageCode": "hr-HR",
        "languageName": "Croatian",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Matej&text={text}",
    },
    "Andika": {
        "languageCode": "id-ID",
        "languageName": "Indonesian",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Andika&text={text}",
    },
    "Rizwan": {
        "languageCode": "ms-MY",
        "languageName": "Malay",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Rizwan&text={text}",
    },
    "Lado": {
        "languageCode": "sl-SI",
        "languageName": "Slovenian",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Lado&text={text}",
    },
    "Valluvar": {
        "languageCode": "ta-IN",
        "languageName": "Tamil (India)",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Valluvar&text={text}",
    },
    "Linda": {
        "languageCode": "en-CA",
        "languageName": "English (Canada)",
        "gender": "Female",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Linda&text={text}",
    },
    "Heather": {
        "languageCode": "en-CA",
        "languageName": "English (Canada)",
        "gender": "Female",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Heather&text={text}",
    },
    "Sean": {
        "languageCode": "en-IE",
        "languageName": "English (Ireland)",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Sean&text={text}",
    },
    "Michael": {
        "languageCode": "de-AT",
        "languageName": "German (Austria)",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Michael&text={text}",
    },
    "Karsten": {
        "languageCode": "de-CH",
        "languageName": "German (Switzerland)",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Karsten&text={text}",
    },
    "Guillaume": {
        "languageCode": "fr-CH",
        "languageName": "French (Switzerland)",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Guillaume&text={text}",
    },
    "Pattara": {
        "languageCode": "th-TH",
        "languageName": "Thai",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Pattara&text={text}",
    },
    "Jakub": {
        "languageCode": "cs-CZ",
        "languageName": "Czech",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Jakub&text={text}",
    },
    "Szabolcs": {
        "languageCode": "hu-HU",
        "languageName": "Hungarian",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Szabolcs&text={text}",
    },
    "Hoda": {
        "languageCode": "ar-EG",
        "languageName": "Arabic (Egypt)",
        "gender": "Female",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Hoda&text={text}",
    },
    "Naayf": {
        "languageCode": "ar-SA",
        "languageName": "Arabic (Saudi Arabia)",
        "gender": "Male",
        "provider": "Azure",
        "limit": 1000,
        "quality": "Medium",
        "translates": False,
        "url": "https://api.streamelements.com/kappa/v2/speech?voice=Naayf&text={text}",
    },
}
